### ISSUE TITLE
simple data split

### ISSUE THREAD

**Issue by sereinexit** [lovefxyo/drawio#1]
哥们，我刷到你在simple的代码下留了一个问题，有关数据集划分的，我也随机划分的8：1：1，但是效果很差，想请教一下哥数据集划分最后怎么弄的呀

**Comment by sawyerfeng** [comment]
> 哥们，我刷到你在simple的代码下留了一个问题，有关数据集划分的，我也随机划分的8：1：1，但是效果很差，想请教一下哥数据集划分最后怎么弄的呀

我觉得效果差和切分数据关系不大，你可以尝试调整负样本比例，或者调整参数以确保模型收敛，或者用新一些大的KGE模型，因为这可能和你数据的特性有关。

**Comment by sereinexit** [comment]
> > 哥们，我刷到你在simple的代码下留了一个问题，有关数据集划分的，我也随机划分的8：1：1，但是效果很差，想请教一下哥数据集划分最后怎么弄的呀
> 
> 我觉得效果差和切分数据关系不大，你可以尝试调整负样本比例，或者调整参数以确保模型收敛，或者用新一些大的KGE模型，因为这可能和你数据的特性有关。

感谢哥的指导，那我的应该是数据集有一些问题，用gpt生成的
Duplicate of #

**Comment by sawyerfeng** [comment]
> > > 哥们，我刷到你在simple的代码下留了一个问题，有关数据集划分的，我也随机划分的8：1：1，但是效果很差，想请教一下哥数据集划分最后怎么弄的呀
> 
> > 
> 
> > 我觉得效果差和切分数据关系不大，你可以尝试调整负样本比例，或者调整参数以确保模型收敛，或者用新一些大的KGE模型，因为这可能和你数据的特性有关。
> 
> 
> 
> 感谢哥的指导，那我的应该是数据集有一些问题，用gpt生成的
> 
> Duplicate of #
华科大佬说笑了，咱可以多交流

**Comment by sereinexit** [comment]
> > > > 哥们，我刷到你在simple的代码下留了一个问题，有关数据集划分的，我也随机划分的8：1：1，但是效果很差，想请教一下哥数据集划分最后怎么弄的呀
> > 
> > 
> > > 
> > 
> > 
> > > 我觉得效果差和切分数据关系不大，你可以尝试调整负样本比例，或者调整参数以确保模型收敛，或者用新一些大的KGE模型，因为这可能和你数据的特性有关。
> > 
> > 
> > 感谢哥的指导，那我的应该是数据集有一些问题，用gpt生成的
> > Duplicate of #
> > 华科大佬说笑了，咱可以多交流

好嘞哥，我卑微学术渣渣

**Comment by sereinexit** [comment]
哥，我想请问一下您有没有跑过对属性三元组建模的链路预测代码
